First iteration
YulyaY/go_final_project pull request #1
Opened 2024-11-27 18:05 UTC by YulyaY

2024-11-28 13:21 UTC, dirtymew requested changes
Привет Юля 

хорошая работа

дал комментарии что поправить - ничего критичного
в целом готов принять работу после правок.

Если планировала делать другие задания со * - то нужно сразу, после того как приму уже на ревью это отправить не получиться

2024-11-28 13:21 UTC, dirtymew commented on README.md
> +В итоговом задании написан на Go веб-сервер, который реализует функциональность простейшего планировщика задач. На главной странице имеется список задач. Можно добавить задачу, отредактировать, удали
отлично что дополнила документацию

2024-11-28 13:21 UTC, dirtymew commented on Makefile
> +build:
мб сделать еще `run` отдельно

2024-11-28 13:21 UTC, dirtymew commented on cmd/service/main.go
> +	fmt.Println("Server is going to start")
стоит еще и порт напечатать

2024-11-28 13:21 UTC, dirtymew commented on internal/domain/model/model.go
> +func Make() Task {
хмм в go так особо не принято... лишняя абстракция 

есть new ...

2024-11-28 13:21 UTC, dirtymew commented on internal/handler/add_task.go
> +	w.Write(result)
_ , _ = w.Write()
тут стоит либо явно проигнорировать ошибку или ее логировать

2024-11-28 13:21 UTC, dirtymew commented on internal/repository/delete_task.go
> +	fmt.Println(affectedCnt)
- лучше логировать на одном уровне логики
 - не стоит все вызовы логировать - можно но тогда стоит взять подвинуты логер с разными уровнями логирования
 - логировать нужно чем-то одним - уже если используешь log то fmt не нужно

2024-11-28 13:21 UTC, dirtymew commented on internal/repository/get_task.go
> +	res := r.db.QueryRow("SELECT * FROM scheduler WHERE id = :id", sql.Named("id", id))
лучше явно поля указывать а не *

2024-11-28 13:21 UTC, dirtymew commented on internal/repository/get_task.go
> +	if t.Id == "" {
этого быть не может - поле контролируется на уровне бд - лишняя проверка

2024-11-28 13:21 UTC, dirtymew commented on internal/repository/get_tasks.go
> +	res, err := r.db.Query("SELECT * FROM scheduler ORDER BY date LIMIT 10")
лимит в константу стоит вынести

2024-11-28 13:21 UTC, dirtymew commented on tests/task_6_test.go
> +	fmt.Println("test update task id=", id)
это стоит убрать

2024-11-28 13:21 UTC, dirtymew commented on tests/tasks_5_test.go
> +	fmt.Println("Unmarshal m: ", m, "Url: ", url)
не дебаж принтами - освой дебагер)

2024-11-30 16:40 UTC, YulyaY commented on Makefile
> +build:
+

2024-11-30 16:50 UTC, YulyaY commented on tests/tasks_5_test.go
> +	fmt.Println("Unmarshal m: ", m, "Url: ", url)
исправлено

2024-11-30 16:50 UTC, YulyaY commented on tests/task_6_test.go
> +	fmt.Println("test update task id=", id)
исправлено

2024-11-30 16:50 UTC, YulyaY commented on internal/repository/get_tasks.go
> +	res, err := r.db.Query("SELECT * FROM scheduler ORDER BY date LIMIT 10")
исправлено

2024-11-30 16:50 UTC, YulyaY commented on internal/repository/get_task.go
> +	if t.Id == "" {
исправлено

2024-11-30 16:50 UTC, YulyaY commented on internal/repository/get_task.go
> +	res := r.db.QueryRow("SELECT * FROM scheduler WHERE id = :id", sql.Named("id", id))
Исправила, указав полный список полей. Дополнительно хочу спросить. Если у меня будет много sql запросов, и я добавлю новый столбец, то мне придется поправить каждый такой запрос. При этом тут есть риск ошибки. Существуют ли какие-то способы минимизировать этот риск и сократить объем работы?

2024-11-30 16:51 UTC, YulyaY commented on internal/repository/delete_task.go
> +	fmt.Println(affectedCnt)
исправлено

2024-11-30 16:51 UTC, YulyaY commented on internal/handler/add_task.go
> +	w.Write(result)
исправлено

2024-11-30 16:51 UTC, YulyaY commented on internal/domain/model/model.go
> +func Make() Task {
исправлено

2024-11-30 16:51 UTC, YulyaY commented on cmd/service/main.go
> +	fmt.Println("Server is going to start")
исправлено

2024-12-06 20:33 UTC, dirtymew commented on internal/repository/get_task.go
> +	res := r.db.QueryRow("SELECT * FROM scheduler WHERE id = :id", sql.Named("id", id))
Есть - использовать ORM типа gorm sqlchemy итд , но в go их не принято использовать )

существуют различные библиотеки для построения запросов... но опять же не очень популярная история. 

просто добавить поле   - это на практике требует сильно больших изменений в проекте и правка запроса самое малое

2024-12-06 20:35 UTC, dirtymew approved these changes
Привет Юлия

работу принимаю 

поздравляю и делаю удачи

2024-12-08 19:55 UTC, merged